steps:

  # 1. Install dependencies and run unit tests
  - name: 'python:3.12-slim'
    id: 'run-tests'
    dir: 'project-1-http-et1'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install --no-cache-dir -r requirements.txt
        python -m pytest

  # 2. Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    dir: 'project-1-http-et1'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/etl-project/http-etl:$SHORT_SHA'
      - '.'

  # 3. Push Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    dir: 'project-1-http-et1'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/etl-project/http-etl:$SHORT_SHA'

  # 4. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-cloud-run'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'sales-etl-service'
      - '--image'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/etl-project/http-etl:$SHORT_SHA'
      - '--region'
      - 'asia-south1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'GOOGLE_CLOUD_PROJECT=$PROJECT_ID'

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/etl-project/http-etl:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY